trigger:
  branches:
    include:
      - main

pool:
  name: 'Default'   # change to your self-hosted pool name if needed

variables:
  buildConfiguration: 'Release'
  packageVersion: '1.0.$(Build.BuildId)'

steps:
- checkout: self
  persistCredentials: true
- task: NuGetAuthenticate@1
  displayName: Authenticate to Azure Artifacts
- task: UseDotNet@2
  displayName: Use .NET 8 SDK
  inputs:
    packageType: 'sdk'
    version: '8.0.x'

- script: |
    dotnet restore ./StringLibSolution/StringExtensions/StringExtensions.csproj
    dotnet restore ./StringLibSolution/ConsumerApp/ConsumerApp.csproj
  displayName: Restore projects

- script: dotnet build ./StringLibSolution/StringExtensions/StringExtensions.csproj -c $(buildConfiguration) --no-restore
  displayName: Build library

- script: dotnet build ./StringLibSolution/ConsumerApp/ConsumerApp.csproj -c $(buildConfiguration) --no-restore
  displayName: Build consumer app

- script: dotnet pack ./StringLibSolution/StringExtensions/StringExtensions.csproj -c $(buildConfiguration) -o $(Build.ArtifactStagingDirectory) /p:PackageVersion=$(packageVersion)
  displayName: Pack NuGet

- task: NuGetAuthenticate@1
  displayName: Authenticate to Azure Artifacts

- script: dir "$(Build.ArtifactStagingDirectory)"
  displayName: Show staged packages

- task: DotNetCoreCLI@2
  displayName: 'Push to Azure Artifacts'
  inputs:
    command: 'push'
    searchPatternPush: '$(Build.ArtifactStagingDirectory)/*.nupkg'
    feedPublish: 'string-extensions-azure/artifacts_in_azure_devops' # Format: Project/Feed
    publishVstsFeed: 'string-extensions-azure/artifacts_in_azure_devops'

